### ISSUE TITLE
Altering Django Admins

### ISSUE THREAD

**Issue by theMissingComma** [istrategylabs/harvest-reaper#16]
Hello Alex,

I have some terribly basic questions related to a previous issue. I have the same issue as before (Signing in as User A outputs hours to User B in a team) with a new user. My previous 'fix' was to create an entirely new gmail account, and start the reaper process from scratch in incognito mode. This is cumbersome and not a continuing fix, but I do not know how to even start accessing the Django admin page.

Unfortunately I am quite new to App integration and Github in general, and have only found your documentation in the 'Development Readme' file. Do I have to create the full environment and follow those outlined processes to access the google account linkages? Or am I able to access the Django from the website URL? I'm slogging through the Djano documentation and I'm woefully in over my head.

If you could point me in the right direction I'd appreciate it. I know you arent continuing work on this project, so sorry for the callback.

Thanks!

**Comment by alexbarbato** [comment]
Ah you bring up a great point!

There is an admin page at ${YOUR_URL}/admin. The login however is a little trickier.

I'm assuming you used the deploy to Heroku button and if so you're going to want to do the following:

1. Download the [Heroku CLI](https://devcenter.heroku.com/articles/getting-started-with-python#set-up) and login with the account you made.
2. Run these commands from your terminal:
```shell
heroku run bash

# It may not put you in the root directory of your project so you may have to cd into it
python manage.py createsuperuser
```
3. Login into the Django Admin with the details you just made and I'd delete any record of the problem users (Social accounts and actual user) and ask them to disconnect their google account's trust for Harvest Reaper. This should totally reset them and allow them to login fresh.

**Comment by alexbarbato** [comment]
Going to close this, but happy to keep chatting as you need support.
